'use strict';

module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('Spots', [
      {
        ownerId: 1,
        address: '3451 Park PI',
        city: 'Pleasanton',
        state: 'California',
        country: 'United States',
        lat: 37.70884568787755,
        lng:  -121.8577699430043,
        name: 'Snuggles Inn - A Dog Family Home',
        description: "A home away from home dog care and cage-free boarding. My family of six (me, my husband, 3 children under 12, Finnley - our sheepadoodle). Our goal is to ensure your dog's stay is a wonderful experience, so they look forward to staying with the family and me time and time again. Either I or my husband will take the dogs out for their morning and evening walks, jogs, or runs depending on the needs of the guest dog. In the afternoon, my children enjoy playing fetch and running around with the dogs in our huge backyard. Finnley, our 4 year-old sheepadoodle is a doggy boot camp graduate and loves the company of all dogs. Finnley is family to us, and in this home, your fur babies will get all the love, affection, and one-on-one attention they would get in their home. Your dog or dogs will have a pawsome time with us, guaranteed! Please don't hesitate to reach out to me if you have any questions - we look forward to meeting you and your dog(s)!",
        price: 165,
        category: 'Dog Home',
        type: 'Dog Family Care',
        pets: 3,
        yard: 'fenced yard',
        children: '3 child under 12',
        personalpets:'1 sheepadoodle',
      },
      {
        ownerId: 4,
        address: '11233 Center St',
        city: 'Brookdale',
        state: 'California',
        country: 'United States',
        lat:  37.11541414647985,
        lng: -122.10566464543096,
        name: "Little Dog Chateaux for the Petite Pup",
        description: "Hello, I am an experienced dog owner of twenty years, offering short-term and long-term boarding for puppies and small dogs. I have experience taking care of puppies and senior dogs, as well as administering medications (orally and injectables), and can also help reinforce things like potty training, basic training commands, and leash manners. My purpose is to provide the best, safest experience for your pup. I currently work from home and will be with your dog 24/7, assuring they have the best care and attention. Your dog will be treated with the same amount of patience, care, and safety that you, yourself would demonstrate. Your dog will also have full access to my home, and I am happy to adjust my schedule to your puppy's needs. My dog, Harley (dachshund), and I look forward to meeting you and your dog. Harley loves other dogs and will be an incredible friend to your dog. Let‘s treat your pup to a pawsitively fun & safe experience!",
        price: 85,
        category: 'Dog Home',
        type: 'Small Dog Care',
        pets: 1,
        yard: 'fenced yard',
        children: '0 children',
        personalpets:'1 dachshund',
      },
      {
        ownerId: 2,
        address: '730 11th Ave',
        city: 'New York',
        state: 'New York',
        country: 'United States',
        lat: 40.77091306390253,
        lng: -73.9939098251481,
        name: "The Cozy Cat: A Comfort Like Home",
        description: "Meow, it's your trusted neighborhood cat sitter here. On the block, I am known as the cat whisperer because I've fostered kitties, adopted older cats and served our feline leaders since 'furever'. Your cat will always be my #1 priority when they are in my care. I have years of experience with cats of all kinds. One of my favorite parts about cat sitting is sending daily photos and updates on how fabulous your cat(s) are doing. Your cats are welcome to my entire home and will have plenty of space to perch, play, and relax. I specialize in offering reassurance and peace of mind to shy & nervous cats and humans too! Your cat(s) will receive all the loving attention in the world with the warm comfort & safety of my house. I currently work from home so I can cater to your cats' needs with my schedules and bring my experience to help you feel comfortable that your cat is in good hands! At The Cozy Cat, your cat or cats will have the best stay of their nine lives!",
        price: 95,
        category: 'Cat Home',
        type: 'Trusted Cat Home',
        pets: 2,
        yard: 'no yard',
        children: '0 children',
        personalpets:'no persona pets',
      },
      {
        ownerId: 20,
        address: '2850 S Quincy St',
        city: 'Arlington',
        state: 'Virginia',
        country: 'United States',
        lat: 38.88423715062414,
        lng: -77.10822080453617,
        name: "Woof’s 'n Whiskers, Pet Care Perfected",
        description: "Here is where furry friendships are made, and unforgettable memories are created. My free-roaming home-environment pet-boarding is safe, secure, and far less stressful and frightening than traditional pet-boarding places. Hi! I am a professional dancer and a huge animal person. Growing up and to this day, my family frequently fostered and adopted cats and dogs. Since moving to Arlington, I have missed caring for fur buddies. What sets me apart from others is my upbeat energy and attentive care. I currently work part-time, so I have plenty of time to play with your kitty or pup! I also live with my brother and his girlfriend, so someone is always at home with your fur baby. We are all animal lovers and can't wait to meet your furry best friend. I am also very observant and attentive and will take great care of your pet. Whatever rules you have at your house, I will keep them in mine!",
        price: 210,
        category: 'Dog Home',
        type: 'Friendly Dog and Cat Care',
        pets: 4,
        yard: 'Fenced Yard',
        children: '0 Children',
        personalpets:'No Personal Pets',
      },
      {
        ownerId: 16,
        address: '12700 Hillcrest Rd',
        city: 'Dallas',
        state: 'Texas',
        country: 'United States',
        lat: 32.96118189543843,
        lng: -96.79548337502388,
        name: "Cat's Cradle: Cage-free, Cats Only Lodging",
        description: "We are a small family of three providing exquisite personalized cat boarding. We are excited to welcome you and your furry friend to our luxury home environment exclusively for cats! Our goal is to provide a stress-free haven for your kitty or kitties. We are a cage-free home with ample room to climb, hide and play. We strive to be as safe as it is comfortable and fun for your pet. We are committed to providing all cat guests with a quality experience. Our house has a lot of natural light, a fenced backyard for our outdoor cat pets, and spots to tuck away and nap. We provide complimentary email, texts, and photo updates every day, three (or more) times a day. Look no further, and no longer worry about what to do with your furry friend when planning a vacation or when suddenly called out of town. We are here to give you the freedom to travel, even on short notice, with the knowledge that your cat(s) are happy and safe in a cat-loving home with dependable and reliable care.",
        price: 150,
        category: 'Cat Home',
        type: 'Cat Family Home',
        pets: 3,
        yard: 'Fenced Yard',
        children: '1 Teenager(14)',
        personalpets:'1 Cat',
      },
      {
        ownerId: 2,
        address: '724 Brazil Ave',
        city: 'San Francisco',
        state: 'California',
        country: 'United States',
        lat:  37.72182854883529,
        lng: -122.4289896459381,
        name: 'Fancy Paws - The Royal Treatment',
        description: "Be a Queen(or King!) and give your adorable feline the royal treatment. Hi, I'm Mia; some of you may recognize my name and my cat, Fat Louie. Yes, I am the Mia, Princess of Genovia. I am back home for a few months to unwind and recharge from my royal duties! My schedule for the upcoming months is to cuddle with as many kitties as possible, as that is my favorite pastime activity. My mother, Fat Louie(my cat), and I open our eccentric firehouse home to all cat pals needing short-term care and lots of cuddles. We only accept one kitty guest at a time, leaving you confident that your cat will be loved as if they were our own. ",
        price: 75,
        category: 'Cat Home',
        type: 'Singular Cat Stay',
        pets: 1,
        yard: 'No Yard',
        children: '0 Children',
        personalpets:'1 White Tabby Cat',
      },
      {
        ownerId: 3,
        address: '11 Washington Square',
        city: 'New York',
        state: 'New York',
        country: 'United States',
        lat:  40.73159338097427,
        lng: -73.99661900355062,
        name: "No Ruff Days, Just Tail Wags and Belly Rubs",
        description: "A home away from home made for your best friend to play while you're away. At the age of six, I knew dogs were my people. At age eight, my parents caved and bought me my first puppy. He (Butter) and I were inseparable, my first best friend. Now, I have two senior dogs, a terrier mix, Cora, and a Goldendoodle, Moose. Both my dogs enjoy having dog guests and are very calm dogs. My girlfriend and I work from home full-time with flexible jobs that can allow us to cater to your dog's routine. We only board animals from one family at a time, your furry friends will be as comfortable here as they would be in your own home. I have comfy dog beds and endless amounts of toys and treats. And for free, I will give your dog belly rubs until my arm falls off. Please also let me know if your pet has special needs such as medication administration, frequent potty breaks, or the need for stimulating or calm environments. We will tailor to their needs to ensure they are healthy and in good care!",
        price: 125,
        category: 'Dog Home',
        type: 'Dog Care',
        pets: 2,
        yard: 'No Yard',
        children: '0 Children',
        personalpets:'2 Dogs',
      },
      {
        ownerId: 5,
        address: '6318 Biscayne Blvd',
        city: 'Miami',
        state: 'Florida',
        country: 'United States',
        lat: 25.8355542567001,
        lng: -80.18619386813756,
        name: "Who is Ready for a Slumber Pawty!",
        description: "Here is your dog's invite to long walks on the beach, lots of cuddles, and warm late nights under the stars. These are just a few perks to booking your dog's stay with my roommates and me. I live with two other females in a big house near the beach. We are all law students and dog lovers who can’t wait to take care of your dog like they're our own! We host a maximum of three dogs at a time, with the exception of dog siblings. So why us? Well, besides living a block away from the beach, and the endless love your pup will receive, we want to provide the best home-away-from-home environment with an enriching experience for your dog. It is important to us to know your pet's feeding schedule in order to keep their environment as consistent as possible. We'd also love to know what they like to do and things that keep them calm, like playing fetch. Additionally please let us know if there is anything that needs to be avoided while your pup is with us.",
        price: 75,
        category: 'Dog Home',
        type: 'Dog Care',
        pets: 2,
        yard: 'Fenced Yard',
        children: '0 children',
        personalpets:'No Personal Pets',
      },
      {
        ownerId: 13,
        address: '158 Wanso Rd',
        city: 'Reserve',
        state: 'Montana',
        country: 'United States',
        lat: 48.621251233704115,
        lng:  -104.8723502269843,
        name: "Paws, Claws, Tails All on Board!",
        description: "Playing, adoring, and tending to your pet is my highest priority. I offer a fun and exciting environment for cats, dogs, rabbits, hamsters, guinea pigs, parrots, and parakeets. My private five-acre farm provides your pets with a unique outdoor and homestyle experience. I believe in a personalized approach to pet care, providing you peace of mind knowing your pet is safe, comfortable, and valued while you’re away. I offer dog owners a free range boarding experience with access to my barns, pastures, and fields. I provide giant pens for bunnies with fresh greens and unlimited hay. I also offer grooming services for all pets. Your pet will experience days full of activity, engagement, and companionship while enjoying the true benefit of farm life. While by my side, your pet will be a part of the family. I will give them the same love and care as if they were my own. Also to help your pet feel at ease before their first overnight stay, I allow day excursions on my farm for your pet.",
        price: 120,
        category: 'Farm Home',
        type: 'Pet Farm Care',
        pets: 2,
        yard: 'Five-Acre Farm',
        children: '0 Children',
        personalpets:'Various Farm Animals',
      },
      {
        ownerId: 7,
        address: '1775 E Bolivar Ave',
        city: ' St Francis',
        state: 'Wisconsin',
        country: 'United States',
        lat: 42.98021272812919,
        lng:  -87.90085051351143,
        name: " The Dog House where Dogs are Family",
        description: "While you roam, they have a home! I specialize in providing quality overnight stays for large dogs. With me, your dog's health, safety, and happiness are always of utmost importance, and I want nothing more than to make your dog's time away from home comfortable and memorable. My home is a no kennel, no cage zone. My home is where pets are family, where playtime is a must, and where there is no such thing as too much attention and affection. A dog's stay with me includes many outdoor activities, access to lots of dog toys, bathing services, and more. I have a fully fenced-in yard and plenty of space in our house for your big dog to roam! I also have security cameras throughout the home. Because I host multiple dogs at a time, safety is my priority. All dogs are actively supervised. I like to send morning and night pictures with updates to you. So whether it's an overnight or a six-month stay, I would be delighted to provide your dog or dogs a home away from home experience.",
        price: 195,
        category: 'Dog Home',
        type: 'Large Dog Care',
        pets: 3,
        yard: 'Fenced Yard',
        children: '0 Children',
        personalpets:'0 Personal Pets',
      },
      {
        ownerId: 12,
        address: '3003 Cypress St,',
        city: 'West Monroe',
        state: 'Louisiana',
        country: 'United States',
        lat: 32.520723651812034,
        lng: -92.15398823346038,
        name: "Exotic Pet Haven: Retipes and Birds Welcomed",
        description: "Not all pets are furry or four-legged! It is sometimes difficult to find a boarding facility that can take care of the needs of your unique pet and offer the attention they require. I offer exotic pet care for birds, reptiles, rabbits, hamsters, guinea pigs, and other small pets. Together, we will personalize your furry, scaly, or feathery friend's stay with their necessary accommodations, diets, feeding schedules, and temperature conditions. I also offer specialized custom ecosystem terrariums & vivariums for our reptile and amphibian guests.  Enjoy unmatched peace of mind knowing your pet is supervised 24/7. Travel confidently! Knowing your exotic pets are in good hands and in a safe home. I provide daily wellness checks on all my pet guests. Every pet is treated as a very important pet (VIP) when they stay with me.",
        price: 250,
        category: 'Exotic Pet Home',
        type: 'Exotic Pet Care',
        pets: 3,
        yard: 'Fenced Yard',
        children: '0 Children',
        personalpets:'2 Birds & 1 Snake',
      },
      {
        ownerId: 11,
        address: ' 567 E Cedar St',
        city: 'Liberal',
        state: 'Kansas',
        country: 'United States',
        lat: 37.04761419213959,
        lng:  -101.02769101180633,
        name: "Paws at Play with Dog Splash Sprinkler",
        description: "There's No Place Like Home! My mission is to provide trustworthy, reliable, loving dog care in the comfort of our home. I know that your furry friend is a cherished member of your family, and I am committed to providing the highest level of care while you're away. My house boasts spacious and comfortable accommodations, ensuring that your dog has plenty of room to stretch out and relax. I have ten years of pet experience and will ensure that your dog's needs are always met because I know that every dog has unique needs and preferences. I am also happy to accommodate any special dietary or medical needs your dog may have, just let me know in advance. When you choose me, you can enjoy peace of mind knowing that your furry friend is in good hands. So let’s get in touch to schedule your dog's stay with me. Your dog will thank you for it!",
        price: 140,
        category: 'Dog Home',
        type: 'Small Dog Care',
        pets: 2,
        yard: 'Fenced Yard',
        children: '0 Children',
        personalpets:'No Personal Pets',
      },
      {
        ownerId: 14,
        address: '524 N Oakley Blvd',
        city: 'Chicago',
        state: 'Illinois',
        country: 'United States',
        lat: 42.55876772438462,
        lng:  -87.67531260379216,
        name: 'Exceptional Care for Modern Pets',
        description: "I believe that every pet deserves the best care and attention possible. My modern, state-of-the-art pet home provided luxurious accommodations that are designed to provide a comfortable and stress-free experience for your furry friends, whether they are cats or dogs. My home features spacious and stylish rooms that are equipped with all the amenities that your pet could need. From cozy beds and soft blankets to interactive toys and climbing structures, your pet will have everything they need to feel right at home. For my dog guests, I offer a variety of indoor and outdoor play activities where they can run, jump, and socialize. For my cat guests, I provide spacious and comfortable rooms with plenty of climbing structures and scratching posts to keep them entertained. I understand that leaving your pet behind can be a stressful experience, which is why I offer regular updates and photos of your pet's stay. Book your pet's stay with me and experience the difference for yourself!",
        price: 175,
        category: 'Cat Home',
        type: 'Dog and Cat Care',
        pets: 2,
        yard: 'Fenced Yard',
        children: '0 Children',
        personalpets:'1 Pomeranian',
      },
      {
        ownerId: 17,
        address: '485 Darling St',
        city: ' Balmain',
        state: 'NSW 2041',
        country: 'Australia',
        lat: -33.85320003719495,
        lng:  151.1731294616828,
        name: "Under our Woof: Personalized Dog Care",
        description: "Welcome to this home of four (me, my husband, my son, and Carter (our dog)), where your furry friend will feel right at home! I know that leaving your dog behind can be a stressful experience, which is why I provide a cozy and welcoming environment that feels just like home. Unlike traditional boarding facilities, we provide individualized attention and care for each and every dog guest. I take the time to get to know each and every guest of mine on a personal level. Whether your dog prefers to play fetch in our spacious backyard, take a leisurely stroll around the neighborhood, or just cuddle up on the couch for a nap, I am here to make sure they have everything they need to feel at home. My family and I will supply plenty of love and attention to our doggie guests, assuring that they feel safe and comfortable throughout their stay. I also offer flexible pick-up and drop-off times to make the process as easy and convenient as possible for you.",
        price: 100,
        category: 'Dog Home',
        type: 'Dog Family Home',
        pets: 2,
        yard: 'Fenced Yard',
        children: '1 Child(10)',
        personalpets:'1 Dog',
      },
      {
        ownerId: 7,
        address: '520 6th St',
        city: 'Havre',
        state: 'Montana',
        country: 'United States',
        lat: 48.78155356133928,
        lng:  -109.71544555802092,
        name: 'Hound Lounge for the Big Dogs',
        description: "I’ve been around animals my whole life and care for them immensely. I’ve owned dogs of various breeds since I was a kid and also have experience with training and administering medicine. What sets me apart is that I understand a pet’s needs, and strive to create a safe environment for any personality. If you choose me, know that I will be attentive, and patient with your dog. I live in a wonderful walking neighborhood that’s nearby a dog park and hiking trails. I have a big fenced-in backyard with tons of plants and trees to sniff! My schedule is easily adaptable and I can accommodate hikes, dog park visits, and extra walks depending on your preference. Dogs can freely wander around the house and I have separate rooms they can hang out in if they need some space. I own two senior dogs(Floss and Flora). They are very loving and patient with other dogs. I also have two children who have grown up around dogs all their lives. Also, my home is open to large dogs of all breeds and sizes.",
        price: 125,
        category: 'Dog Home',
        type: 'Big Dog Care',
        pets: 3,
        yard: 'Fenced Yard',
        children: '2 Children',
        personalpets:'2 Big Dogs',
      },
      {
        ownerId: 10,
        address: '20246 N Rand Rd',
        city: 'Palatine',
        state: 'Illinois',
        country: 'United States',
        lat: 42.239019484850914,
        lng: -88.0300789089151,
        name: "Wee Little Paws Inn",
        description: "I currently work from home full time so I have plenty of time to dedicate to your pup and have the flexibility to take them out for walks throughout the day. My daily routine always includes playing with your pup, and providing fun and active adventures! I love taking walks as a source of exercise and bonding time with a dog. I provide regular potty breaks that are between every 2-4 hours. Also, there will be lots of cuddles included. Your dog will be in good company with my dog Newton. We have plenty of toys and dog beds to keep your dog happy and comfortable. Your pup is guaranteed to be spoiled with love and attention! Safety is of the utmost importance. I am mindful of our environment and closely supervise and monitor the pets in our care. Proactive care, attention, activity, and anticipating your pet's needs are tools to help ensure a safe environment. Please let me know of any special care needs ahead of time so I can be sure to accommodate them.",
        price: 140,
        category: 'Dog Home',
        type: 'Small Dog Care',
        pets: 3,
        yard: 'Fenced Backyard',
        children: '0 Children',
        personalpets:'1 Yorkshire Terrier',
      },
      {
        ownerId: 4,
        address: '130 S Redwood Rd',
        city: 'North Salt Lake',
        state: 'Utah',
        country: 'United States',
        lat: 41.65034061548318,
        lng:  -111.51379402210041,
        name: "Dog’s Den: Happy Paws,Happy Life",
        description: "Animals have always been a part of my life.I have yet to meet an animal that I don’t love. In my mind,they should be spoiled and showered with affection at every opportunity. Their unconditional love is heartwarming and deserves to be rewarded with lots of cuddles. I take care of only small and medium-sized dogs up to 40 pounds and over 1 year old. I have experience in administering medication in liquid, injection, and pill form. Your fur baby is my priority. Your dog is my only job so my time is spent feeding, playing with, and caring for your pup, 24 hours a day. I will be taking pictures of your baby throughout their stay and will forward updates at your request. I have a secure multi-gated yard that makes it easy to keep your baby safe, even if they are an escape artist. I have artificial turf, bark, and pebble landscaping so your baby will not come home with burrs or unwelcomed bugs. I take pride in providing a safe and welcoming environment for every dog, tail wags guaranteed.",
        price: 120,
        category: 'Dog Home',
        type: 'Small/Medium Dog Care',
        pets: 2,
        yard: 'Fenced Yard',
        children: '0 Children',
        personalpets:'0 Personal pets',
      },
      {
        ownerId: 11,
        address: '101 Mission Ct',
        city: 'Franklin',
        state: 'Tennesse',
        country: 'United States',
        lat: 36.09251942456685,
        lng:  -86.83977030412373,
        name: "Happiest Paws- Never Home Alone",
        description: "We are a small family of three and huge dog lovers. My husband has extensive knowledge and experience with dog care and training. My son is 10 but has had hands-on experience raising and caring for animals through both us and Cub Scouts. Your pet will be in loving hands from all three of us around the clock. I am home full-time, so your pet will not be left alone or uncared for at any time. We are glad to provide photos and updates throughout the duration of your pet's time with us. Our home has a large backyard for play and sunshine time. We have a clean patio area great for sunbathing if desired. Our backyard also has a garden where they can enjoy the scents of fresh citrus, rosemary, and in warmer months a variety of herbs. We will treat your dog as a part of our family while they stay with us. I look forward to welcoming and caring for your pup!",
        price: 65,
        category: 'Dog Home',
        type: 'Dog Care',
        pets: 1,
        yard: 'Large Fenced Yard',
        children: '1 Child(10)',
        personalpets:'0 Personal Pets',
      },
      {
        ownerId: 8,
        address: '7327 4th St NW',
        city: 'Los Ranchos De Albuquerque',
        state: 'New Mexico',
        country: 'United States',
        lat: 35.71971751026834,
        lng:  -106.61701969127098,
        name: 'Canine Country Club',
        description: "Our canine country club is a family-forward stay providing many activities and services such as grooming, training, boarding, and socialization opportunities. I’m available to care for the dogs all day and ensure your dogs get lots of exercise and attention. We have a large outdoor play area and lots of indoor play spaces. My husband and I prioritize providing a safe and enjoyable environment for dogs to socialize, exercise, and receive the care and attention they require. We are an active family and enjoy taking the dogs to dog parks, hiking trails, and walks around the block. We follow a consistent schedule that keeps the pups busy! We normally start the day with breakfast and a walk. Then lots of play in the yard throughout the day. Our evenings include a walk and time on the couch with lots of cuddles before dinner and bedtime. I send lots of photos of our day. This is a great option for busy pet owners who want to ensure that their dogs are well cared for while they are away.",
        price: 110,
        category: 'Dog Home',
        type: 'Dog Care',
        pets: 2,
        yard: 'Fenced Yard',
        children: '2 Children',
        personalpets:'1 Golden Retriever',
      },
      {
        ownerId: 18,
        address: '2607 S 11th St',
        city: 'Niles',
        state: 'Michigan',
        country: 'United States',
        lat: 41.874962223942205,
        lng:  -86.2040396960402,
        name: "The Cat's Meow: Experience Great Cat Care",
        description: "Welcome to The Cat's Meow,where your feline friends will feel right at home while you're away. My cozy homes provide a comfortable and secure environment for cats of all ages and sizes.My home has plenty of toys, scratching posts, and climbing structures to keep your cat entertained during their stay. I have over 10 years of experience working with felines and am well-educated to handle any medical or behavioral issues that may arise. I always make time for individualized playtime to make sure your cat feels loved and cared for. There will be plenty of cuddles and snuggles too. I'm an amicable, responsible, and attentive person. I'm also a great problem-solver. If you choose to allow me to take care of such an important part of your life, I'll be sure to make your pet my priority during my time with him/her. I communicate well and am always easily reached so there would be no worries. All cats must be up to date on their vaccinations and spayed or neutered before their stay here.",
        price: 105,
        category: 'Cat Home',
        type: 'Cat Care',
        pets: 2,
        yard: 'No Yard',
        children: 'No Children',
        personalpets:'No Personal Cats',
      },
      {
        ownerId: 16,
        address: '2808 NE Martin Luther King Jr Blvd',
        city: 'Portland',
        state: 'Oregon',
        country: 'United States',
        lat: 45.69680598588373,
        lng: -122.6238707209876,
        name: 'Pounce Play and Stay Cat Home',
        description: "Pounce Play and Stay isn't your typical boarding, more like a home away from home stay. I am a feline-only home located in the Eliot-Irvington neighborhood, near the Nike store. You will not find metal cages, cramped spaces, or loud noise here. I can accommodate cats of all ages, sizes, and abilities. All stays have access to multiple scratching posts, cat climbing towers, giant window seats, wall perches, filtered water fountains, sofas, and cat-safe plants!  Plus, there's plenty of interactive play, kitty socialization, brushing, massaging, and snuggles to go around! With over two decades of animal welfare experience, I am dedicated to pet safety and consistent, outstanding, customer satisfaction and support.  My animal expertise and specialized knowledge combined with my ability to meet the pet’s physical, emotional, and psychological needs come together in a fun, safe, and comfortable environment that makes Pounce the perfect option for pets and their owners.",
        price: 135,
        category: 'Cat Home',
        type: 'Cat Care',
        pets: 3,
        yard: 'No Yard',
        children: '0 Children',
        personalpets:'1 Residential Cat',
      },
      {
        ownerId: 2,
        address: '415 NE 80th Ave',
        city: ' Portland',
        state: 'Oregon',
        country: 'United States',
        lat: 45.727336382139555,
        lng:  -122.51132395419019,
        name: 'Cats in the City: Cat Boarding Done Right',
        description: "My cat-only home is designed to give your cat a positive experience. I have lots of windows for viewing, cat trees for climbing, beds for napping, cubbies for hiding, posts for scratching, and toys for playing.  At Cats in the City, my top priority is the health of the cats in our care. I track and record all food and water consumed, and all liquid and solid waste is eliminated. I measure hydration levels, monitor weight when needed, and I test blood sugar levels when appropriate. Doing this allows me to respond, adapt, and meet the physical and emotional needs of cats boarding with me.  All cats have full access to explore the common areas, playrooms, and catio at any time. I keep careful watch over my furry guests. I follow your instructions regarding feeding, medications, and other care needs. I am also skilled at taking care of cats with special needs, including older animals with low mobility. We commonly administer insulin, oral medications, injections, and Sub-Q fluids.",
        price: 175,
        category: 'Cat Home',
        type: 'Cat Care',
        pets: 3,
        yard: 'Fenced Yard',
        children: '0 Children',
        personalpets:'0 Personal Pet',
      },
      {
        ownerId: 15,
        address: '604 S Jefferson Ave',
        city: 'West Jefferson',
        state: 'North Carolina',
        country: 'United States',
        lat: 36.59776768178669,
        lng: -81.46939303917992,
        name: 'Bed, Bath, and Bones: A Dog Home',
        description: "Don't worry about leaving your dog alone while you are away. Instead, leave your dog in the care of someone you can trust. Bring your dog to experience the ultimate in comfort and pampering with luxury accommodations at Bed, Bath, and Bones. I go beyond just taking care of your dog. I make all my dog guests feel comfortable and at ease with the same love, care, and cozy attention they would find at home. I make sure every pet parents know their four-legged family member is well taken care of when they stay overnight with me. I schedule plenty of fun activities to ensure your dog will stay happy and active all day long - just like a dog should be! Whether your dog is gracefully graying or simply requires a special diet or medication, I can certainly accommodate you. I can administer medications to your pup and I can also continue their special diet or food preparation. Just let me know ahead of time what your needs are.",
        price: 95,
        category: 'Dog Home',
        type: 'Dog Care',
        pets: 1,
        yard: 'Fenced Yard',
        children: 'No Children',
        personalpets:'No Residential Pet',
      },
      {
        ownerId: 8,
        address: '522 Soaring Eagle Trail',
        city: 'Wichita Falls',
        state: 'Texas',
        country: 'United States',
        lat: 33.81862334204251,
        lng: -98.41719749428405,
        name: 'Bed and Biscuits Country Inn',
        description: "Are you looking for a place for your dog while you are out of town or having work done on your home?We are a family home providing the safest and cleanest atmospheres that unleash the happiest home away from home experience for your dog(s). Our cage-free indoor and outdoor spaces provide your dog time to socialize, exercise, play, and sleep. At the same time, we provide round-the-clock supervision and care. Our stay offers the happiness of living in the country. Where we offer invigorating playtime with peaceful nap time throughout the day. At night we all sleep safe and sound inside the home, dreaming of dancing dog biscuits. You can rest easy while away, knowing that my home is located next door to a first-class veterinarian hospital, should the need arise. Also, let us know your pet’s feeding schedule, general tendencies, and activity level. Any unique quirks are also good to share and if they have any preferences that we could follow to make them happier, we would love to know!",
        price: 250,
        category: 'Dog Home',
        type: 'Dog Care',
        pets: 2,
        yard: 'Fenced Backyard',
        children: '1 Child',
        personalpets:'1 Dog',
      },
      {
        ownerId: 15,
        address: '280 N El Camino Real',
        city: 'Encinitas',
        state: 'California',
        country: 'United States',
        lat: 33.23206830689424,
        lng: -117.21083361955367,
        name: 'Paw Commons for Dog People',
        description: "I know that pet parents have many choices when it comes to finding overnight pet care, but when you board with me, it’s an opportunity for socialization that will help your dog become more comfortable with other dogs and new people. As your dog learns to get along with others and becomes a good canine citizen, the results are often better overall behavior. It’s a positive cycle that allows you to include your dog in more of your regular outings and experiences. And let’s face it, when your dog can tag along almost anywhere, life just gets more fun – for both of you! While they stay here, your pet can expect plenty of exercise throughout their day. Plus, I offer password-protected webcams that allow you to be a fly on the wall and look in on all the fun! The daily routine includes eating, sleeping, and playing. I am happy to accommodate any special feedings or medication needs your dog may have. I look forward to serving you the next time you need fun, reliable overnight pet care!",
        price: 55,
        category: 'Dog Home',
        type: 'Dog Care',
        pets: 1,
        yard: 'Fenced Yard',
        children: '0 Children',
        personalpets:'No Personal Pets',
      },
      {
        ownerId: 19,
        address: '1 Farley Ln',
        city: 'Alton',
        state: 'Staffordshire',
        country: 'United Kingdom',
        lat: 52.990708895705886,
        lng:-1.8950692465337766,
        name: 'Hippity Hop: A Rabbit & Bunny Lodge',
        description: "Welcome to Hippity Hop Lodging and Care, your premier destination for rabbit care!  While you are away, you can trust your bunny’s care to our rabbit-savvy staff. Your rabbit will receive hands-on, experienced care in a rabbit-friendly environment. Our boarding facility offers Fresh Oxbow timothy hay, Crisp salads twice a day, Daily exercise time in an individual playpen, A personal bunny condo (Bunny can bring his or her own blanket and toy!), A rabbit-perfect temperature, Ability to give medicines twice daily, Grooming during your rabbit’s stay, if requested (additional spa fee for services), And no barking dogs! We strive to provide transparent communication, offering updates and photos to keep you informed and connected with your furry companions. Trust us with your rabbits' care, and let us provide them with a safe and enjoyable boarding experience.",
        price: 75,
        category: 'Rabbit/Bunny Home',
        type: 'Rabbit and Bunny Care',
        pets: 4,
        yard: 'Fenced Yard',
        children: '0',
        personalpets:'No Personal Pets',
      },
      {
        ownerId: 19,
        address: '2901 N Clark St',
        city: 'Chicago',
        state: 'Illinois',
        country: 'United States',
        lat: 41.95647608060533,
        lng: -87.64867914480389,
        name: 'Harebnb: The Perfect Getaway for Your Rabbit!',
        description: "Are you planning a vacation or a business trip but worried about who will take care of your rabbit? Look no further! Harebnb is here to provide a comfortable and enjoyable stay for your precious rabbits while you're away. We offer top-notch care in a safe and stimulating environment, ensuring your rabbit feel right at home. We are well-versed in rabbit care and know how to handle and interact with rabbits, providing them with the love, attention, and care they deserve. Each rabbit will have its own spacious and cozy hutch, complete with cushy bedding, ample space to hop around, and hiding spots for privacy. We know the importance of a balanced diet for rabbits. We provide fresh hay, vegetables, and high-quality pellets according to your rabbit's dietary needs. Special dietary requirements? No problem! Just let us know, and we'll ensure your bunny's needs are met. We regularly check their appetite, behavior, and litter box habits to ensure they're happy and healthy during their stay.",
        price: 50,
        category: 'Rabbit/Bunny Home',
        type: 'Rabbit and Bunny Hotel',
        pets: 3,
        yard: 'Fenced Yard',
        children: 'No Children',
        personalpets:'No Personal Pets',
      },
      {
        ownerId: 15,
        address: '3531 Surrey Dr',
        city: 'Saline',
        state: 'Michigan',
        country: 'United States',
        lat: 42.20855209923052,
        lng: -83.79843928466002,
        name: "Woodstock's Bird Care and Boarding",
        description: "Woodstock's Bird Care provides family-based bird boarding for bird guardians like you who may be traveling, working long hours, recovering from an illness, renovating/selling your home, or away for another reason. Our primary goal is for you to relax and feel confident that you are giving your birds the highest quality care even when you are away. Unlike traditional pet sitters, we provide daily cage-free recreation time, fresh fruits and vegetables, and companionship with our bird-friendly staff and other avian residents and guests. Reserve your dates today.",
        price: 40,
        category: 'Bird Home',
        type: 'Family Bird Home',
        pets: 2,
        yard: 'Fenced Yard',
        children: 'No Children',
        personalpets:'2 cockatiel',
      },
      {
        ownerId: 1,
        address: '747 E Thunderbird Rd',
        city: 'Phoenix',
        state: 'Arizona',
        country: 'United States',
        lat: 33.60636614330147,
        lng: -112.06335058675137,
        name: 'Second Home Pet Retreat',
        description: "Are you a proud owner of multiple pets? We understand the joys and challenges that come with managing a household filled with furry, feathery, and/or scaly friends. That's why we're here to offer our pet boarding services designed specifically for multi-pet homes. We welcome dogs, cats, birds, rabbits, guinea pigs, hamsters, and reptiles. With our expertise and personalized approach, you can ensure that each of your pets receives the love, attention, and care they deserve. We'll ensure that each of your pets has their own cozy resting area, complete with comfortable bedding and toys, allowing them to relax and unwind in peace. Made with great thought and care, our 16,500-square-foot home is filled with special touches that assure each of your pets is comfortable and safe while staying with us. Additionally, we text or e-mail you with regular updates, including photos and reports, so you can have peace of mind while you're away.",
        price: 160,
        category: 'Multiple Pet Home',
        type: 'All Pet Care',
        pets: 4,
        yard: 'Open Yard',
        children: 'No Children',
        personalpets:'No Personal Pets',
      },
      {
        ownerId: 18,
        address: '500 Columbian Street',
        city: 'South Weymouth',
        state: 'Massachusetts',
        country: 'United States',
        lat: 42.18025177861378,
        lng:  -70.97259721706841,
        name: 'Slither and Stay: Reptitle Care',
        description: "Are you going on a trip and don’t have anywhere to leave your reptile pet? Slither and Stay offers overnight stays for your reptile pets! Our boarding services are limited to snakes, amphibians, turtles, and lizards. Your reptile friend will be cared for by my husband, a veterinarian, and me, a veterinary technician. Our home has multiple temperature-controlled rooms that can be tailored to your reptile needs. We do daily cage cleanings and individualized care. You must supply your pet’s caging while boarding with us. Reptitle animals stress easily and if they can continue to be in their familiar cages and receive the same foods, it will limit their anxiety while in new surroundings. Also, bringing their own food helps to alleviate stomach upset usually associated with abrupt changes in diet. Owners of reptiles with special needs should speak with us before leaving their pets. We can happily administer any medications, supplements, or vitamins while your pet is boarding with us.",
        price: 50,
        category: 'Reptile Home',
        type: 'Professional Reptitle Care',
        pets: 2,
        yard: 'No yard',
        children: 'No Children',
        personalpets:'2 Snakes & 1 Turtle',
      },
      {
        ownerId: 13,
        address: '3401 Irving St',
        city: 'San francisco',
        state: 'California',
        country: 'United States',
        lat: 37.76337849813584,
        lng:  -122.49441328466004,
        name: 'Pocket Pals: Guinea pigs, hamsters, rats & more',
        description: "Pocket Pals is here for you and the littlest members of your family. The small pets we board include guinea pigs, hamsters, rats, and chinchillas. Unlike a commercial facility, we offer an in-home experience with no barking dogs, no meowing cats, stainless steel cages, and silence and darkness after hours.  We pride ourselves on the way we take care of our animals. We know that when you go away on vacation, you are looking for experienced compassionate caretakers to watch your little loved ones. Having boarded animals for the past 30 years, you won't find a more qualified home to care for your pets! We provide audio-visual stimulation by showing animated and kid-friendly movies all day long. We also include a full update regarding eating habits, bowel movements, daily health checks, and overall well-being.",
        price: 100,
        category: 'Hamster/Guinea Pig Home',
        type: 'Small Animal Care',
        pets: 4,
        yard: 'No Yard',
        children: 'No Children',
        personalpets:'No Personal Pets',
      },
      {
        ownerId: 13,
        address: '7427 Norton Rd',
        city: ' Hiram',
        state: 'Ohio',
        country: 'United States',
        lat: 41.345532198302664,
        lng: -81.12673775830312,
        name: 'Cavy Cove: A Guinea Pigs Paradise',
        description: "At Cavy Cove, guinea pigs are always treated as if they were on vacation! Care service includes veggies for breakfast, hay for lunch, pellets for dinner, and a light veggie or fruit for an evening snack. Of course, there is always an abundance of hay and water available in each piggie's habitat. Activities are important! We have plenty to keep your guinea pig busy! Friendly piggies get the chance to watch awesome movies (like G-Force) while munching on a salad. Usually, 3-5 guinea pigs get to watch a movie together on one of the tablets. Playtime is a great experience and gives your guinea pig a chance to meet other piggies. Playtime is always supervised and can be done solo if your guinea pig isn’t into socializing. All guinea pig habitats are cleaned daily. If you have bonded piggies, they will be kept segregated from other bonded piggies so that there is less of a chance of unbonding. Upon request, we can send you text picture updates of your guinea pig(s).",
        price: 40,
        category: 'Hamster/Guinea Pig Home',
        type: 'Guinea Pig home',
        pets: 2,
        yard: 'No Yard',
        children: '1 teenager(15) & 1 child(8)',
        personalpets:'1 guinea pig',
      },
      {
        ownerId: 1,
        address: '3114 Cherokee St NW',
        city: ', Kennesaw',
        state: 'Georgia',
        country: 'United States',
        lat: 34.223997626099475, 
        lng: -84.56842889401946,
        name: "Cottontail Cottage for Bunnies",
        description: "Welcome to Cottontail Cottage, where all bunnies are warmly embraced! I offer unique in-home bunny boarding services, designed for owners seeking a special place for their furry friend. With over 20 years of experience as a dedicated bunny owner, I am devoted to providing exceptional care. Unlike traditional pet-sitting arrangements where pets are left alone for extended periods, I ensure that your bunny is never left unattended. I supply all the necessary housing essentials, including organic, farm-fresh hay, litter boxes, bedding, water bowls, and hideaways. During your bunny's stay, they will enjoy a nutritious diet consisting of daily vegetables such as a mix of leafy greens, carrots, broccoli, and celery. Your bunny will be encircled with relaxing music, abundant sunshine, and ample space for play, ensuring a stimulating and enjoyable environment. I prioritize daily housekeeping and thoroughly disinfecting suites between guests to maintain a clean and healthy environment for all.",
        price: 80,
        category: 'Rabbit/Bunny Home',
        type: 'Rabbit Care',
        pets: 2,
        yard: 'Fenced Yard',
        children: 'No Children',
        personalpets:'2 Rabbits',
      },
      
    ], {});
  },
  async down(queryInterface, Sequelize) {
    const Op = Sequelize.Op;
    await queryInterface.bulkDelete('Spots', null, {});
  }
};
